metadata:
  name: edge-all
  version: 0.0.1
  notes: |
    TODO: Add remaining modules and packages
spec:
  source: src/utils
  artifact:
    kind: tar.gz
    dst: artifacts/utils.tar.gz
  build:
    include: [ 'utils/*', 'utils/**/*' ]
    # include: [ 'utils/**/*' ]
    exclude: [ ]
