metadata:
  name: stable-testing
  version: 0.0.1
spec:
  source: src/
  artifact:
    kind: tar.gz
    dst: utils.tar.gz
  build:
    name: utils
    pkg:
      modules:
        testing:
          module:
            kind: pythonModule
            src: testing.py
            dst: testing.py
      pkgs: {}