metadata:
  name: stable-all
  version: 0.0.1
  notes: |
    Currently this is just the same as the `all` configuration.
    WebApp Utilities are currently actively under development.
spec:
  source: src/
  artifact:
    kind: tar.gz
    dst: utils.tar.gz
  build:
    name: utils
    pkg:
      requirements: requirements.txt # Path relative to the Package
      modules:
        errors:
          module:
            kind: pythonModule
            src: errors.py
            dst: errors.py
        filesystem:
          module:
            kind: pythonModule
            src: filesystem.py
            dst: filesystem.py
        itertools:
          module:
            kind: pythonModule
            src: itertools.py
            dst: itertools.py
        metrics:
          module:
            kind: pythonModule
            src: metrics.py
            dst: metrics.py
      pkgs:
        concurrency:
          requirements: concurrency/requirements.txt # Path relative to the SubPackage
          init:
            kind: pythonInit
            src: concurrency/__init__.py
            dst: concurrency/__init__.py
          pkgs:
            aio:
              init:
                kind: pythonInit
                src: concurrency/aio/__init__.py
                dst: concurrency/aio/__init__.py
              modules:
                fd:
                  module:
                    kind: pythonModule
                    src: concurrency/aio/fd.py
                    dst: concurrency/aio/fd.py
                linux:
                  module:
                    kind: pythonModule
                    src: concurrency/aio/linux.py
                    dst: concurrency/aio/linux.py
                watch:
                  module:
                    kind: pythonModule
                    src: concurrency/aio/watch.py
                    dst: concurrency/aio/watch.py
            gates:
              init:
                kind: pythonInit
                src: concurrency/gates/__init__.py
                dst: concurrency/gates/__init__.py
        kvstore:
          requirements: kvstore/requirements.txt # Path relative to the SubPackage
          init:
            kind: pythonInit
            src: kvstore/__init__.py
            dst: kvstore/__init__.py
          pkgs:
            backends:
              modules:
                disk:
                  module:
                    kind: pythonModule
                    src: kvstore/backends/disk.py
                    dst: kvstore/backends/disk.py
        web:
          requirements: web/requirements.txt # Path relative to the SubPackage
          init:
            kind: pythonInit
            src: web/__init__.py
            dst: web/__init__.py
          modules:
            app:
              module:
                kind: pythonModule
                src: web/app.py
                dst: web/app.py
